[project]
name = "ii"
version = "0.0.1"
description = "wip meme"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "dateparser>=1.2.2",
    "loguru>=0.7.3",
    "nicegui>=2.22.2",
    "pywebview>=6.0",
    "requests>=2.32.4",
]
